In [66]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrices import accuracy_score
from sklearn.metrices import meansquared

In [ ]:
"C:\Users\BHARGAVI\OneDrive\Documents\all_season_details.csv"

In [67]:
df=pd.read_csv(r"C:\Users\BHARGAVI\OneDrive\Documents\all_season_details.csv")

C:\Users\BHARGAVI\AppData\Local\Temp\ipykernel_4220\139627852.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\BHARGAVI\OneDrive\Documents\all_season_details.csv")

In [68]:
df

,comment_id,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,...,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt,text,preText,postText
0,110,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"nice and full, angling and perhaps swinging in...",<p><strong>7.30pm</strong> Gaikwad and Conway ...,NaN
1,120,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"Conway shuffles across off, and shimmies out a...",NaN,NaN
2,130,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"good length, angling in at off and then straig...",NaN,NaN
3,140,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"shorter and slanting into middle and leg, Gaik...","<p>Rummy: ""Fast bowling options for CSK defini...",NaN
4,150,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Shami hits a heavy length and brings this back...,"<p>LG: ""Watching out for Hangargekar. He was i...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242545,219020,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,2,...,NaN,NaN,NaN,NaN,NaN,NaN,False,lovely! Balaji's bowled a yorker outside off s...,NaN,NaN
242546,219030,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,3,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne steps down the track and throws his bat ...,NaN,<p>6 off 3 balls.</p>
242547,219050,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne reaches out for a full ball and squeezes...,NaN,<p>Three to win off two balls.</p>
242548,219040,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,...,NaN,NaN,NaN,NaN,NaN,NaN,False,what has he done! Balaji has bowled a wide out...,<p>Rajasthan need two runs a ball. Balaji from...,NaN
242549,219060,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,5,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Balaji bowls a full toss angling into the left...,NaN,<p>Rajasthan need one off the final ball.</p>

In [69]:
print(df.head())

   comment_id  season  match_id match_name home_team away_team  \
0         110  2023.0   1359475   GT v CSK        GT       CSK
1         120  2023.0   1359475   GT v CSK        GT       CSK
2         130  2023.0   1359475   GT v CSK        GT       CSK
3         140  2023.0   1359475   GT v CSK        GT       CSK
4         150  2023.0   1359475   GT v CSK        GT       CSK

  current_innings  innings_id  over  ball  ...  wicket_id wkt_batsman_name  \
0             CSK           1     1     1  ...        NaN              NaN
1             CSK           1     1     2  ...        NaN              NaN
2             CSK           1     1     3  ...        NaN              NaN
3             CSK           1     1     4  ...        NaN              NaN
4             CSK           1     1     5  ...        NaN              NaN

   wkt_bowler_name  wkt_batsman_runs  wkt_batsman_balls  wkt_text  \
0              NaN               NaN                NaN       NaN
1              NaN               NaN                NaN       NaN
2              NaN               NaN                NaN       NaN
3              NaN               NaN                NaN       NaN
4              NaN               NaN                NaN       NaN

  isRetiredHurt                                               text  \
0         False  nice and full, angling and perhaps swinging in...
1         False  Conway shuffles across off, and shimmies out a...
2         False  good length, angling in at off and then straig...
3         False  shorter and slanting into middle and leg, Gaik...
4         False  Shami hits a heavy length and brings this back...

                                             preText  postText
0  <p><strong>7.30pm</strong> Gaikwad and Conway ...       NaN
1                                                NaN       NaN
2                                                NaN       NaN
3  <p>Rummy: "Fast bowling options for CSK defini...       NaN
4  <p>LG: "Watching out for Hangargekar. He was i...       NaN

[5 rows x 45 columns]

In [70]:
x=df[['over','wicket_id']]
y=df['wkt_batsman_runs']

In [71]:
x

        over  wicket_id
0          1        NaN
1          1        NaN
2          1        NaN
3          1        NaN
4          1        NaN
...      ...        ...
242545    20        NaN
242546    20        NaN
242547    20        NaN
242548    20        NaN
242549    20        NaN

[242550 rows x 2 columns]

In [72]:
y

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
242545   NaN
242546   NaN
242547   NaN
242548   NaN
242549   NaN
Name: wkt_batsman_runs, Length: 242550, dtype: float64

In [23]:
split=0.8
train_size=int((len(df))*split)

In [24]:
train_data=data[:train_size]
test_data=data[train_size:]

In [25]:
train_data

,comment_id,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,...,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt,text,preText,postText
0,110,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"nice and full, angling and perhaps swinging in...",<p><strong>7.30pm</strong> Gaikwad and Conway ...,NaN
1,120,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"Conway shuffles across off, and shimmies out a...",NaN,NaN
2,130,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"good length, angling in at off and then straig...",NaN,NaN
3,140,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"shorter and slanting into middle and leg, Gaik...","<p>Rummy: ""Fast bowling options for CSK defini...",NaN
4,150,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,5,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Shami hits a heavy length and brings this back...,"<p>LG: ""Watching out for Hangargekar. He was i...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194035,117060,2011.0,501240,CSK v RR,CSK,RR,RR,1,18,5,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"full, slower ball and straight and goes over t...",NaN,NaN
194036,117070,2011.0,501240,CSK v RR,CSK,RR,RR,1,18,6,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"fullish ball, driven with some force to long-o...",NaN,NaN
194037,118010,2011.0,501240,CSK v RR,CSK,RR,RR,1,19,1,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"cut away, square of the wicket, Morkel starts ...",NaN,NaN
194038,118020,2011.0,501240,CSK v RR,CSK,RR,RR,1,19,2,...,NaN,NaN,NaN,NaN,NaN,NaN,False,full and chopped to long-off,NaN,NaN
194039,118030,2011.0,501240,CSK v RR,CSK,RR,RR,1,19,3,...,277916.0,Ajinkya Rahane,Albie Morkel,4.0,8.0,AM Rahane c &amp; b Morkel 4 (8b 0x4 0x6) SR: ...,False,Rahane walks across his stumps to get hold of ...,NaN,NaN

In [26]:
test_data

,comment_id,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,...,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt,text,preText,postText
194040,118040,2011.0,501240,CSK v RR,CSK,RR,RR,1,19,4,...,38699.0,Ross Taylor,Albie Morkel,20.0,14.0,LRPL Taylor c Hussey b Morkel 20 (14b 2x4 0x6)...,False,"full delivery, Taylor takes a big step forward...",NaN,NaN
194041,118050,2011.0,501240,CSK v RR,CSK,RR,RR,1,19,5,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"doesn't get it, length delivery, outside off, ...",NaN,NaN
194042,118060,2011.0,501240,CSK v RR,CSK,RR,RR,1,19,6,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"driven into the covers, sucessful last over fo...",NaN,NaN
194043,119010,2011.0,501240,CSK v RR,CSK,RR,RR,1,20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"fullish and on leg stump, clubbed down to mid-on",NaN,NaN
194044,119020,2011.0,501240,CSK v RR,CSK,RR,RR,1,20,2,...,NaN,NaN,NaN,NaN,NaN,NaN,False,"full toss and played down to deep cover, thoug...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242545,219020,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,2,...,NaN,NaN,NaN,NaN,NaN,NaN,False,lovely! Balaji's bowled a yorker outside off s...,NaN,NaN
242546,219030,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,3,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne steps down the track and throws his bat ...,NaN,<p>6 off 3 balls.</p>
242547,219050,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne reaches out for a full ball and squeezes...,NaN,<p>Three to win off two balls.</p>
242548,219040,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,...,NaN,NaN,NaN,NaN,NaN,NaN,False,what has he done! Balaji has bowled a wide out...,<p>Rajasthan need two runs a ball. Balaji from...,NaN
242549,219060,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,5,...,NaN,NaN,NaN,NaN,NaN,NaN,False,Balaji bowls a full toss angling into the left...,NaN,<p>Rajasthan need one off the final ball.</p>

In [27]:
x_train, x_test,y_train ,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [28]:
x_train

        over  wicket_id
199032    12        NaN
237647    17        NaN
10462      1        NaN
39475      8        NaN
137928     9        NaN
...      ...        ...
119879    10   219889.0
103694    12        NaN
131932     5        NaN
146867    18        NaN
121958    10        NaN

[194040 rows x 2 columns]

In [29]:
x_test

        over  wicket_id
122566    10        NaN
147656     5        NaN
27099     20        NaN
42493      2        NaN
154359    18        NaN
...      ...        ...
19877     17        NaN
217199    14        NaN
188029     2        NaN
220380    14        NaN
8762       5        NaN

[48510 rows x 2 columns]

In [30]:
y_train

199032     NaN
237647     NaN
10462      NaN
39475      NaN
137928     NaN
          ...
119879    28.0
103694     NaN
131932     NaN
146867     NaN
121958     NaN
Name: wkt_batsman_runs, Length: 194040, dtype: float64

In [31]:
y_test

122566   NaN
147656   NaN
27099    NaN
42493    NaN
154359   NaN
          ..
19877    NaN
217199   NaN
188029   NaN
220380   NaN
8762     NaN
Name: wkt_batsman_runs, Length: 48510, dtype: float64

In [33]:
data.shape

(242550, 45)

In [52]:
rf_model=RandomForestClassifier(n_estimators=200,max_depth=None,random_state=42)
rf_model

RandomForestClassifier(n_estimators=200, random_state=42)

In [86]:
rf_simple_mse=mean_squared_error(y_test,y_pred)
rf_r2=r2_score(y_test,y_pred)

In [44]:
data1=pd.DataFrame({
    'overs_bowled':[10],
    'wickets_lost':[0],
    'run_rate':[10],
    'powerplay':[0]
})

In [45]:
data1

   overs_bowled  wickets_lost  run_rate  powerplay
0            10             0        10          0

In [58]:
runp=rf_model.predict(new_data)
runp

In [58]:
array([102.9])